### ISSUE TITLE
reporter can see all reports

### ISSUE THREAD

**Issue by gregoiredx** [ACRA/acralyzer#125]
Hello,

Is there a way to prevent a "reporter" user to read existing reports?

Reporter user credentials being embedded in mobile apps, couldn't they be easily found by decompiling apk?
Thus giving anybody access to all reports...

Am I wrong. Did I misconfigure something?

Anyway, thank you for this cool app.

**Comment by secu2** [comment]
This is due to a couchdb limitation, a workaround is documented here :
https://github.com/ACRA/acralyzer/wiki/Setting-up-a-reverse-proxy

**Comment by gregoiredx** [comment]
ok, thank you
