### ISSUE TITLE
Cant replicate, 503 error

### ISSUE THREAD

**Issue by itayrabin** [ACRA/acralyzer#130]
both links that are needed to be replicated with couchdb return a 503 error 
i.e:
http://get.acralyzer.com/distrib-acralyzer
and http://get.acralyzer.com/distrib-acra-storage are returning 503

**Comment by scemodicecosa** [comment]
same thing with me

**Comment by fabbroniko** [comment]
same here

**Comment by KevinGaudin** [comment]
I'm sorry guys, I'm still maintaining this server without actively monitoring it.
I restarted it, looks good to me.
Thanks for reporting.

**Comment by scemodicecosa** [comment]
thanks you!

**Comment by EmmanuelMess** [comment]
Error reappeared; should I open another issue?

**Comment by KevinGaudin** [comment]
I'll restart it in a moment. Stay tuned. ;-)

**Comment by KevinGaudin** [comment]
Fixed.
