### ISSUE TITLE
Please provide instructions how to mirror get.acralyzer.com

### ISSUE THREAD

**Issue by pmajkutewicz** [ACRA/acralyzer#134]
I see that others also ahve a problem to get acra running (#133). Can You provide instruction how to provide http://get.acralyzer.com/distrib-acra-storage and http://get.acralyzer.com/distrib-acralyzer locally eg. docker.

I think if others would be able to replicate from different source than it is win-win for everyone. You have smaller traffic on acralyzer.com, everyone interested is able to get app running.

**Comment by KevinGaudin** [comment]
If get.acralyzer.com does not work, you can still use the "manual setup" page of the wiki: https://github.com/ACRA/acralyzer/wiki/manual-setup.
get.acralyzer.com/distrib-acra-storage and get.acralyzer.com/distrib-acralyzer are just hosted in a CouchDB instance behind an apache+mod_proxy server.

**Comment by KevinGaudin** [comment]
Also, I'm really sorry that I can't maitain Acralyzer anymore. Though I'm quite sure there are now many alternatives that are far easier to use, more efficient and full-featured.

**Comment by pmajkutewicz** [comment]
@KevinGaudin 
I'm aware of new "full-featured" alternatives. But I've already one "bug db" in alcalyzer and currently I'm trying to migrate it to docker. And I've read a "manual setup", but cauchapp link is also dead, and I don't know couchdb that much.

> get.acralyzer.com/distrib-acra-storage and get.acralyzer.com/distrib-acralyzer are just hosted in a CouchDB instance behind an apache+mod_proxy server.
Oh. I think now i understand. Those endpoints provides empty DB + acralyzer app. I've assumed there has to be something more.
Now, one way or another I'll be able to get it running. Thank You.
