### ISSUE TITLE
http://get.acralyzer.com/distrib-acralyzer not working

### ISSUE THREAD

**Issue by xlc1540697096** [ACRA/acralyzer#136]
http 502, slow, help me

**Comment by F43nd1r** [comment]
Duplicate of #133

**Comment by Fahriya** [comment]
I can not replicate db from http://get.acralyzer.com/distrib-acra-storage , always returns   {http_error_code,503,<<"GET http://get.acralyzer.com/distrib-acra-storage/">>}
