### ISSUE TITLE
Acralyzer behind apache with proxypass

### ISSUE THREAD

**Issue by hannesa2** [ACRA/acralyzer#65]
When I run Acralyzer behind apache with

```
    ProxyPass /acra http://local-ip:5984 nocanon
    ProxyPassReverse /acra http://local-ip:5984
```

When I use it

```
    http://servername/acra/acralyzer/_design/acralyzer/index.html#/dashboard/
```

I get a **unable to connect to couchdb**
This works perfect:

```
    http://servername:5984/acralyzer/_design/acralyzer/index.html#/dashboard/
```

Do you know, where I have to change the db connect ?

**Comment by agrueneberg** [comment]
I ran into the same problem and submitted a pull request to fix it: #106

**Comment by Okeanos** [comment]
Uh … I don't suppose this will be fixed anytime soon in the official branch?

**Comment by agrueneberg** [comment]
Depends on @KevinGaudin. I think it's safe to merge.

**Comment by halkeye** [comment]
I did a quick review and give it a +1

**Comment by amineDev** [comment]
+1
